package commands

import (
	"fmt"
	"strings"
)

// commandref.go renders the GENERATED slash-command reference from COMMAND_REGISTRY.
//
// Same anti-drift reasoning as the tool reference (internal/app/capabilityref.go): the
// command surface was being restated by hand in README.md, and had already fallen behind
// — commands lived in the registry and were missing from the README block, so
// the two commands a tester needs FIRST were the two the documentation did not mention.
// Generating from the registry makes that failure impossible.
//
// It lives in this package rather than alongside the tool reference because
// internal/commands already imports internal/app; the reverse would be an import cycle.

const commandRefHeader = `<!-- Code generated by internal/commands/commandref.go. DO NOT EDIT. -->
<!-- Regenerate with: go test ./internal/commands -run TestGeneratedCommandRefIsCurrent -update -->
`

// RenderCommandReference renders every slash command, in registry order — which is a
// product contract (it drives the palette and /help ordering), not an alphabetisation.
func RenderCommandReference() string {
	var b strings.Builder
	b.WriteString(commandRefHeader)
	b.WriteString("\n# Slash commands (generated)\n\n")
	b.WriteString("Every command the cockpit and the classic REPL accept, projected from\n")
	b.WriteString("`COMMAND_REGISTRY` (`internal/commands/registry.go`) — the same table that drives the\n")
	b.WriteString("composer palette and `/help`, so this cannot describe a command that does not exist\n")
	b.WriteString("or omit one that does.\n\n")
	b.WriteString("Most commands work in both surfaces — the cockpit renders them as command cards (and\n")
	b.WriteString("may focus a deck view), while `--classic` prints them to the console. One does not:\n")
	b.WriteString("`/approvals` is cockpit-only, since session approvals are a cockpit concept.\n\n")
	b.WriteString("**Do not edit this file** — it is regenerated and diffed in CI.\n\n")

	fmt.Fprintf(&b, "## %d commands\n\n", len(COMMAND_REGISTRY))
	b.WriteString("| Command | What it does |\n|---|---|\n")
	for _, c := range COMMAND_REGISTRY {
		fmt.Fprintf(&b, "| `%s` | %s |\n", c.Syntax, cellText(c.Help))
	}

	b.WriteString("\n## Aliases\n\n")
	b.WriteString("Handled by the parsers, deliberately absent from the registry so they do not clutter\n")
	b.WriteString("the palette:\n\n")
	b.WriteString("| Alias | Command |\n|---|---|\n")
	b.WriteString("| `/?` | `/help` |\n")
	b.WriteString("| `/q`, `/exit` | `/quit` |\n")
	return b.String()
}

// cellText makes a help string safe inside a Markdown table cell.
//
// Two hazards, both present in the real registry: a `|` ends the cell early, and an
// angle-bracket placeholder like <id> is parsed as inline HTML and VANISHES from the
// rendered page — so `/memory pin <id>` displayed as "pin" and the argument the reader
// needed was simply gone.
func cellText(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "<", "&lt;")
	s = strings.ReplaceAll(s, ">", "&gt;")
	return s
}
