#!/usr/bin/env python3
"""Regenerate src/ui/splash/frames.ts — the Daintree boot-splash logo reveal.

Recreates the app's own logo-reveal (public/skeleton-logo.js) as a perfectly-
symmetric ASCII animation. The mark is a hand-tuned essence of the logo: a wide
canopy arch, detached by a clear gap from a central trunk and two roots. It is split
into components (a flood-fill cleanly separates the detached canopy from the trunk
and roots) and revealed in the real sequence:

    trunk  — grows bottom-up
    roots  — grow bottom-up, staggered after the trunk
    canopy — draws on a 45° diagonal from the bottom-outer corners up and inward,
             the two arch halves meeting at the top-centre peak last.

Every frame is mirror-symmetric by construction (we render the left half and mirror
it). Pure Python, no external deps. Run from the repo root:

    python3 scripts/gen-splash.py
"""
import collections, json, os

ART = [
    "..................############..................",
    "..............####################..............",
    "..........#########..........#########..........",
    "........#######................#######..........",
    "......######..........####..........######......",
    "....######............####............######....",
    "...#####..............####..............#####...",
    "..#####....####.......####.......####....#####..",
    "..####....######......####......######....####..",
    "..####.....######.....####.....######.....####..",
    "..####.......####.....####.....####.......####..",
    "...###.......####.....####.....####.......###...",
    ".............####.....####.....####.............",
    ".............####.....####.....####.............",
    ".............####.....####.....####.............",
    "......................####......................",
    "......................####......................",
    "......................####......................",
]
W = 48
H = len(ART)
C = W // 2          # mirror seam / left-half width
N = 20              # frames
BLOCK = "█"

assert all(len(r) == W for r in ART), [len(r) for r in ART]
# Mirror the left half onto the right for guaranteed symmetry, then flood-fill.
A = [r[:C] + r[:C][::-1] for r in ART]
fill = [[A[r][c] == "#" for c in range(W)] for r in range(H)]
comp = [[-1] * W for _ in range(H)]
cid = 0
for r in range(H):
    for c in range(W):
        if fill[r][c] and comp[r][c] < 0:
            q = collections.deque([(r, c)])
            comp[r][c] = cid
            while q:
                y, x = q.popleft()
                for dy, dx in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                    ny, nx = y + dy, x + dx
                    if 0 <= ny < H and 0 <= nx < W and fill[ny][nx] and comp[ny][nx] < 0:
                        comp[ny][nx] = cid
                        q.append((ny, nx))
            cid += 1
# The canopy is whatever touches the top rows; the trunk is the central branch; the
# rest are roots.
canopy = {comp[r][c] for r in range(2) for c in range(W) if fill[r][c]}
trunk = {comp[r][c] for r in range(H) for c in (C - 1, C) if fill[r][c] and comp[r][c] not in canopy}
projs = [c - r for r in range(H) for c in range(C) if fill[r][c] and comp[r][c] in canopy]
pmin, pmax = min(projs), max(projs)

def ease(t):  # ease-out
    t = max(0.0, min(1.0, t))
    return 1 - (1 - t) ** 2

def win(g, a, b):  # eased progress of one stage's [a,b] window over global g
    return ease((g - a) / (b - a)) if g > a else 0.0

def cell_on(r, c, tp, rp, cp):
    if not fill[r][c]:
        return False
    k = comp[r][c]
    if k in canopy:                              # 45° diagonal, outer-bottom -> peak
        return cp > 0 and cp >= ((c - r) - pmin) / (pmax - pmin)
    if k in trunk:                               # bottom-up
        return tp >= (H - 1 - r) / (H - 1)
    return rp >= (H - 1 - r) / (H - 1)           # roots, bottom-up

def frame(g):
    tp, rp, cp = win(g, 0.00, 0.42), win(g, 0.16, 0.62), win(g, 0.40, 1.00)
    rows = []
    for r in range(H):
        left = "".join(BLOCK if cell_on(r, c, tp, rp, cp) else " " for c in range(C))
        rows.append(left + left[::-1])           # mirror -> perfect symmetry
    return "\n".join(rows)

frames = [frame(f / (N - 1)) for f in range(N)]

out = [
    "// AUTO-GENERATED by scripts/gen-splash.py — do not edit by hand.",
    "// A perfectly-symmetric ASCII recreation of the Daintree logo-reveal: trunk grows",
    "// up, then roots, then the canopy arch draws on a 45° diagonal from the bottom-outer",
    "// corners up to the centre peak (which connects last). The mark is the essence of the",
    "// logo — a wide canopy detached by a clear gap from a central trunk and two roots.",
    "",
    f"export const SPLASH_WIDTH = {W};",
    f"export const SPLASH_HEIGHT = {H};",
    "",
    "export const SPLASH_FRAMES: readonly string[] = [",
]
out += ["  " + json.dumps(f) + "," for f in frames]
out += ["];"]
dst = os.path.join(os.path.dirname(__file__), "..", "src", "ui", "splash", "frames.ts")
open(dst, "w").write("\n".join(out) + "\n")
print(f"wrote {os.path.relpath(dst)}: {len(frames)} frames, {W}x{H}")
